# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.7.1-18-g8c04365
_src_path: https://github.com/algorandfoundation/algokit-react-frontend-template
algod_port: 4001
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
author_email: chris.kim@algorand.foundation
author_name: Chris Kim
cloud_provider: netlify
ide_vscode: true
indexer_port: 8980
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
project_name: frontend
use_daisy_ui: false
use_eslint_prettier: true
use_github_actions: false
use_jest: false
use_playwright: false
use_tailwind: true

