# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.1-22-gd5c2296
_src_path: https://github.com/algorandfoundation/algokit-fullstack-template
author_email: chris.kim@algorand.foundation
author_name: Chris Kim
cloud_provider: none
contract_name: charity_crowdfunding
ide_vscode: true
preset_name: starter
project_name: charity-crowdfunding-algokit
python_linter: none
use_dispenser: false
use_github_actions: true
use_python_black: true
use_python_mypy: false
use_python_pip_audit: true
use_python_pytest: true

